esphome:
  name: remote
esp8266:
  board: sparkfunBlynk
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
logger:
api:
  encryption:
    key: !secret remote_api
ota:
  - platform: esphome
    password: !secret ota_password
switch:
  - platform: restart
    name: "Living Room Restart"
status_led:
  pin: GPIO0
remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%
button:
  - platform: template
    name: "TV Off"
    id: tv_pwr_toggle
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xED12
  - platform: template
    name: "TV input"
    id: tv_input
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xF00F
  - platform: template
    name: "TV 5"
    id: tv_5
    on_press:
      remote_transmitter.transmit_nec:
          address: 0xBF40
          command: 0xFA05
  - platform: template
    name: "TV 6"
    id: tv_6
    on_press:
      remote_transmitter.transmit_nec:
          address: 0xBF40
          command: 0xF906
  - platform: template
    name: "TEAC AI-101DA Off"
    id: av_pwr_toggle
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x7280
        command: 0xFD02
  - platform: template
    name: "TEAC AI-101DA VOL HI"
    id: av_vol_up
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF802
  - platform: template
    name: "TEAC AI-101DA VOL LO"
    id: av_vol_down
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF806
  - platform: template
    name: "SMSL Audio Off"
    id: av_smsl_pwr_toggle
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF801         
  - platform: template
    name: "SMSL Audio Input"
    id: av_smsl_input
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF807
  - platform: template
    name: "SMSL Audio Left"
    id: av_smsl_left
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF803
  - platform: template
    name: "SMSL Audio Right"
    id: av_smsl_right
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF805
  - platform: template
    name: "SMSL Audio Middle"
    id: av_smsl_middle
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF804
  - platform: template
    name: "SMSL Audio EQ"
    id: av_smsl_eq
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF808
  - platform: template
    name: "SMSL Audio Mute"
    id: av_smsl_mute
    on_press:
      remote_transmitter.transmit_nec:
        address: 0x3412
        command: 0xF809                                             